# Base configuration
# Keys without a value are passed into the config via a .env file in the same
# directory as the `docker-compose` command was run from
services:
  app:
    image: octri.ohsu.edu/omop_annotator
    volumes:
      - ./target/omop_annotator.jar:/app.jar
      - ./docker_data/search_indices:/search_indices
    environment:
      - SERVER_SERVLET_CONTEXTPATH
      - APP_DATASOURCE_URL
      - APP_DATASOURCE_USERNAME
      - APP_DATASOURCE_PASSWORD
      - LDAP_CONTEXTSOURCE_URL
      - LDAP_CONTEXTSOURCE_USERDN
      - LDAP_CONTEXTSOURCE_PASSWORD
      - LDAP_CONTEXTSOURCE_SEARCHBASE
      - LDAP_CONTEXTSOURCE_SEARCHFILTER
      - LDAP_CONTEXTSOURCE_ORGANIZATION
      - OMOP_DATASOURCE_DRIVERCLASSNAME
      - OMOP_DATASOURCE_URL
      - OMOP_DATASOURCE_USERNAME
      - OMOP_DATASOURCE_PASSWORD
      - OMOP_DATA_REFRESHDATE
      - OMOP_DATA_DATEFORMAT
      - SEARCH_BACKEND_DIRECTORY_ROOT=search_indices
