# Local default environment overrides, useful for development environments
services:
  app:
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - APP_DATASOURCE_URL=jdbc:mysql://mysql/omop_annotator?serverTimezone=America/Los_Angeles
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=omop_annotator
      - MYSQL_USER=omop_annotator
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
