# Imports an optional configuration to use for local development.
spring.config.import=optional:dev.properties

spring.mustache.prefix=classpath:/mustache-templates/
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.request-context-attribute=req

app.name=@project.artifactId@
app.version=@project.version@
app.displayName=OMOP Annotator

server.servlet.context-path=/omop_annotator
server.forward-headers-strategy=native

logging.level.org.hibernate=ERROR
logging.level.org.springframework.boot=ERROR
logging.level.org.springframework.security=INFO

#
# Persistence properties
#

spring.flyway.locations=classpath:db/migration/{vendor}

# Application data source
app.datasource.url=jdbc:mysql://localhost:3306/omop_annotator?serverTimezone=America/Los_Angeles
app.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.datasource.username=omop_annotator
app.datasource.password=omop_annotator

app.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# OMOP data source
omop.datasource.url=
omop.datasource.driver-class-name=
omop.datasource.username=
omop.datasource.password=

omop.hibernate.dialect=
omop.hibernate.default-schema=

omop.data.refreshDate=
omop.data.dateFormat=yyyy-MM-dd HH:mm:ss

spring.data.rest.base-path=api

# Metrics
management.endpoint.metrics.access=read-only
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=read-only
management.prometheus.metrics.export.enabled=true

# Disable high-cardinality http_server_requests_seconds* metrics by default.
management.observations.enable.http.server.requests=false
management.observations.enable.spring.security=false

#
# Authentication Library Properties
#

octri.authentication.enable-ldap=true
octri.authentication.enable-table-based=false
octri.authentication.routes.default-login-success-url=/
octri.authentication.routes.logout-success-url=/
#octri.authentication.username-style=plain
#octri.authentication.password-token-valid-for=30m

# LDAP authentication configuration
ldap.context-source.url=
ldap.context-source.user-dn=
ldap.context-source.password=
ldap.context-source.search-base=
ldap.context-source.search-filter=
ldap.context-source.organization=
ldap.context-source.email-domain=

# Configure to enable password reset emails for table-based accounts
#spring.mail.from=
#spring.mail.default-encoding=UTF-8
#spring.mail.host=
#spring.mail.port=
#spring.mail.protocol=
#spring.mail.test-connection=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=
#spring.mail.properties.mail.smtp.starttls.enable=
#spring.mail.properties.mail.smtp.starttls.required=

# Allow override of authentication library beans
spring.main.allow-bean-definition-overriding=false

# Swallow the constraint violation exception logged by this class since the app handles it
logging.level.org.hibernate.engine.jdbc.spi.SqlExceptionHelper=off

# https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/#backend-lucene
# Typically these would be prefixed with 'spring.jpa.properties.hibernate.', but we are using
# multiple data sources so we need to pass these properties in manually. See:
# SearchConfig and OmopDataSourceConfiguration for details.
search.backend-type=lucene
search.backend-directory-root=search_indices
search-indexing.batch-size=900