---
name: Build and test
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:

jobs:
  build-java-source:
    name: Build jar and test
    uses: OHSU-OCTRI/shared-workflows/.github/workflows/java-test-build.yaml@main
    with:
      java_version: '17'

  run-node-tests:
    name: Run Node.js tests
    uses: OHSU-OCTRI/shared-workflows/.github/workflows/node-test.yaml@main
    with:
      node_version: '24.x'
